package spring.boot.gemini.model.type;

public enum SafetyCategory {
    HARM_CATEGORY_UNSPECIFIED,
    HARM_CATEGORY_HARASSMENT,
    HARM_CATEGORY_HATE_SPEECH,
    HARM_CATEGORY_SEXUALLY_EXPLICIT,
    HARM_CATEGORY_DANGEROUS_CONTENT,
}
